// Convert country name to flag emoji
export const getCountryFlag = (country: string): string => {
  const countryFlags: Record<string, string> = {
    'USA': '🇺🇸',
    'United States': '🇺🇸',
    'UK': '🇬🇧',
    'United Kingdom': '🇬🇧',
    'Japan': '🇯🇵',
    'France': '🇫🇷',
    'Italy': '🇮🇹',
    'Germany': '🇩🇪',
    'Netherlands': '🇳🇱',
    'South Korea': '🇰🇷',
    'Korea': '🇰🇷',
    'Canada': '🇨🇦',
    'China': '🇨🇳',
    'Sweden': '🇸🇪',
    'Denmark': '🇩🇰',
    'Norway': '🇳🇴',
    'Belgium': '🇧🇪',
    'Spain': '🇪🇸',
    'Portugal': '🇵🇹',
    'Australia': '🇦🇺',
    'Brazil': '🇧🇷',
    'Argentina': '🇦🇷',
    'Chile': '🇨🇱',
    'Nigeria': '🇳🇬',
    'Kenya': '🇰🇪',
    'Senegal': '🇸🇳',
    'United Arab Emirates': '🇦🇪',
    'UAE': '🇦🇪',
    'Malaysia': '🇲🇾',
    'Czech Republic': '🇨🇿',
    'Poland': '🇵🇱',
    'Vietnam': '🇻🇳',
    'Indonesia': '🇮🇩',
    'Singapore': '🇸🇬',
    'Hong Kong': '🇭🇰',
    'Taiwan': '🇹🇼',
    'Mexico': '🇲🇽',
    'Thailand': '🇹🇭',
    'India': '🇮🇳',
    'Philippines': '🇵🇭',
    'Colombia': '🇨🇴',
    'South Africa': '🇿🇦',
    'Turkey': '🇹🇷',
    'Russia': '🇷🇺',
    'Greece': '🇬🇷',
    'Austria': '🇦🇹',
    'Switzerland': '🇨🇭',
    'New Zealand': '🇳🇿',
    'Ireland': '🇮🇪',
    'Romania': '🇷🇴',
    'Hungary': '🇭🇺',
    'Morocco': '🇲🇦',
    'Ghana': '🇬🇭',
    'Egypt': '🇪🇬',
    'Jamaica': '🇯🇲',
    'Peru': '🇵🇪',
    'Ukraine': '🇺🇦',
    'Finland': '🇫🇮',
    'Croatia': '🇭🇷',
    'Rwanda': '🇷🇼',
    'Tanzania': '🇹🇿',
    'Uganda': '🇺🇬',
    'Cameroon': '🇨🇲',
    'Ivory Coast': '🇨🇮',
    "Côte d'Ivoire": '🇨🇮',
    'Ethiopia': '🇪🇹',
    'Zimbabwe': '🇿🇼',
    'Botswana': '🇧🇼',
    'Mozambique': '🇲🇿',
    'Namibia': '🇳🇦',
    'Togo': '🇹🇬',
    'Benin': '🇧🇯',
    'Burkina Faso': '🇧🇫',
    'Democratic Republic of Congo': '🇨🇩',
    'DR Congo': '🇨🇩',
    'Angola': '🇦🇴',
    'Mauritius': '🇲🇺',
    'Madagascar': '🇲🇬',
    'Burundi': '🇧🇮',
    'Mali': '🇲🇱',
    'Guinea': '🇬🇳',
    'Gabon': '🇬🇦',
    'Somalia': '🇸🇴',
    'Sudan': '🇸🇩',
    'Tunisia': '🇹🇳',
    'Algeria': '🇩🇿',
    'Libya': '🇱🇾',
    'Zambia': '🇿🇲',
  };

  return countryFlags[country] || '🌍';
};

// Export sorted country list for dropdowns
export const getCountryList = (): { name: string; flag: string }[] => {
  const countries = [
    'Algeria', 'Angola', 'Argentina', 'Australia', 'Austria', 'Belgium',
    'Benin', 'Botswana', 'Brazil', 'Burkina Faso', 'Burundi', 'Cameroon',
    'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Czech Republic',
    'DR Congo', 'Denmark', 'Egypt', 'Ethiopia', 'Finland', 'France',
    'Gabon', 'Germany', 'Ghana', 'Greece', 'Guinea', 'Hong Kong',
    'Hungary', 'India', 'Indonesia', 'Ireland', 'Italy', 'Ivory Coast',
    'Jamaica', 'Japan', 'Kenya', 'Libya', 'Madagascar', 'Malaysia',
    'Mali', 'Mauritius', 'Mexico', 'Morocco', 'Mozambique', 'Namibia',
    'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Peru',
    'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Rwanda',
    'Senegal', 'Singapore', 'Somalia', 'South Africa', 'South Korea',
    'Spain', 'Sudan', 'Sweden', 'Switzerland', 'Taiwan', 'Tanzania',
    'Thailand', 'Togo', 'Tunisia', 'Turkey', 'UAE', 'UK', 'Uganda',
    'Ukraine', 'USA', 'Vietnam', 'Zambia', 'Zimbabwe',
  ];
  return countries.map(name => ({ name, flag: getCountryFlag(name) }));
};
