-- Add brief descriptions to brands that currently have none
UPDATE brands SET description = CASE slug
  WHEN 'apresse' THEN 'Japanese contemporary label crafting refined, understated wardrobe essentials'
  WHEN 'aaron-esh' THEN 'London-based designer blending British tailoring with raw streetwear energy'
  WHEN 'acne-studios' THEN 'Swedish luxury house known for minimalist design and iconic denim'
  WHEN 'ader-error' THEN 'Seoul-based label mixing playful graphics with oversized silhouettes'
  WHEN 'alaa' THEN 'Legendary Parisian couture house celebrated for sculptural, body-conscious design'
  WHEN 'allsaints' THEN 'British contemporary brand fusing rock-inspired edge with modern essentials'
  WHEN 'aries' THEN 'London skate-rooted label known for bold prints and tie-dye techniques'
  WHEN 'ashley-williams' THEN 'British designer delivering irreverent, punk-infused womenswear'
  WHEN 'asics' THEN 'Japanese sportswear giant renowned for performance running shoes and retro collabs'
  WHEN 'auralee' THEN 'Tokyo-based label specialising in premium fabrics and quiet luxury'
  WHEN 'barbour' THEN 'Iconic British heritage brand famous for waxed jackets since 1894'
  WHEN 'beyond-retro' THEN 'Vintage curators offering hand-picked secondhand and upcycled fashion'
  WHEN 'billionaire-boys-club' THEN 'Pharrell-founded streetwear label blending hip-hop culture with bold graphics'
  WHEN 'born-x-raised' THEN 'LA-born streetwear brand rooted in West Coast Chicano culture'
  WHEN 'bottega-veneta' THEN 'Italian luxury house iconic for its signature intrecciato leather weave'
  WHEN 'brain-dead' THEN 'Creative collective producing graphic-heavy, subculture-driven streetwear'
  WHEN 'casio-g-shock' THEN 'Indestructible Japanese watches built for extreme durability and style'
  WHEN 'chopova-lowena' THEN 'London duo blending Bulgarian folklore with punk-inspired silhouettes'
  WHEN 'clsc' THEN 'American streetwear brand offering clean, classic everyday essentials'
  WHEN 'craig-green' THEN 'Visionary British designer known for sculptural, workwear-inspired pieces'
  WHEN 'daily-paper' THEN 'Amsterdam-based label celebrating African heritage through modern streetwear'
  WHEN 'deadsea-london' THEN 'London vintage dealer specialising in rare archive and deadstock pieces'
  WHEN 'derschutze' THEN 'German streetwear label with dark, military-influenced aesthetics'
  WHEN 'doomsday-co' THEN 'UK brand delivering apocalyptic-themed graphics and punk-inspired designs'
  WHEN 'dukes-cupboard' THEN 'Legendary London vintage store curating rare designer archive pieces'
  WHEN 'erdem' THEN 'British-Canadian designer renowned for romantic florals and couture craftsmanship'
  WHEN 'everything-hip-hop' THEN 'UK retailer dedicated to authentic hip-hop culture and streetwear'
  WHEN 'fatface' THEN 'British lifestyle brand inspired by outdoor adventure and coastal living'
  WHEN 'felt' THEN 'LA-based skate brand blending California surf culture with streetwear'
  WHEN 'heresy' THEN 'UK label drawing from British folklore, paganism and craft traditions'
  WHEN 'hornets' THEN 'Emerging brand with a distinctive edge and bold graphic identity'
  WHEN 'issey-miyake' THEN 'Pioneering Japanese house famous for pleating technology and architectural design'
  WHEN 'jaded-london' THEN 'London label known for bold, festival-ready and gender-fluid fashion'
  WHEN 'jordan-brand' THEN 'Iconic sneaker line born from Michael Jordan legacy and basketball culture'
  WHEN 'juice' THEN 'Hong Kong-rooted streetwear boutique and brand curating global street culture'
  WHEN 'jw-anderson' THEN 'Anglo-Irish designer celebrated for gender-fluid fashion and playful luxury'
  WHEN 'kartik-research' THEN 'Indian designer reviving artisan techniques through contemporary menswear'
  WHEN 'lazy-oaf' THEN 'London label delivering bold, colourful and irreverent graphic-driven fashion'
  WHEN 'lemaire' THEN 'Parisian house offering refined, timeless wardrobe pieces with quiet elegance'
  WHEN 'mrc-noir' THEN 'French streetwear label known for tactical aesthetics and utility design'
  WHEN 'maha' THEN 'Amsterdam sneaker and streetwear boutique championing independent brands'
  WHEN 'mardi-mercredi' THEN 'Seoul-born lifestyle brand with cheerful, pastel-toned casual essentials'
  WHEN 'no-faith-studios' THEN 'UK streetwear label exploring themes of rebellion and counter-culture'
  WHEN 'noah' THEN 'NYC brand blending prep, punk and environmentalism into elevated streetwear'
  WHEN 'nora' THEN 'Independent label with a focus on thoughtful, well-crafted basics'
  WHEN 'on' THEN 'Swiss performance brand revolutionising running with CloudTec cushioning'
  WHEN 'only-ny' THEN 'New York label inspired by the outdoors, fishing and city life'
  WHEN 'our-legacy' THEN 'Swedish brand reinterpreting heritage fabrics through a modern lens'
  WHEN 'percival' THEN 'London menswear label crafting relaxed, elevated everyday clothing'
  WHEN 'perks-and-mini' THEN 'Australian duo creating psychedelic, art-driven streetwear since 2000'
  WHEN 'pestle-mortar' THEN 'Malaysian streetwear brand with Southeast Asian-rooted design and graphics'
  WHEN 'pigalle' THEN 'Parisian label bridging basketball culture with high-fashion streetwear'
  WHEN 'pop-trading-company' THEN 'Dutch skate brand producing clean, European-influenced skate apparel'
  WHEN 'public-culture' THEN 'UK collective merging art, music and streetwear into a cultural platform'
  WHEN 'puma' THEN 'German sportswear giant blending athletics with fashion-forward collaborations'
  WHEN 'qasimi' THEN 'London-Dubai label exploring displacement and identity through sharp tailoring'
  WHEN 'quiet-life' THEN 'LA skate brand celebrating the laid-back California creative lifestyle'
  WHEN 'ragtag' THEN 'Japanese resale chain specialising in curated designer secondhand fashion'
  WHEN 'real-mccoys' THEN 'Japanese label obsessively reproducing vintage Americana with artisan quality'
  WHEN 'reternity' THEN 'European streetwear brand with a focus on timeless, minimal aesthetics'
  WHEN 'rick-owens' THEN 'Avant-garde designer known for dark, dramatic and sculptural fashion'
  WHEN 'rokit' THEN 'London vintage institution offering rare finds and curated streetwear'
  WHEN 'ronnin' THEN 'Independent streetwear label with refined, minimalist graphic design'
  WHEN 'sacrifice' THEN 'Emerging brand delivering bold, uncompromising streetwear with attitude'
  WHEN 'simone-rocha' THEN 'Irish-London designer known for romantic, tulle-laden feminine silhouettes'
  WHEN 'size' THEN 'UK sneaker retailer with exclusive collaborations and curated streetwear'
  WHEN 'skims' THEN 'Shapewear and essentials brand by Kim Kardashian redefining inclusivity'
  WHEN 'slam-jam' THEN 'Italian streetwear institution connecting underground culture with global fashion'
  WHEN 'tony-delfino' THEN 'Independent label with character-driven graphics and streetwear roots'
  WHEN 'triads' THEN 'UK retailer curating premium streetwear and contemporary fashion brands'
  WHEN 'true-religion' THEN 'American denim brand famous for bold stitching and statement jeans'
  WHEN 'uniqlo' THEN 'Japanese essentials giant offering quality basics and designer collaborations'
  WHEN 'unlimited-legacy' THEN 'Emerging label building a legacy through premium streetwear design'
  WHEN 'veld' THEN 'Independent brand crafting distinctive, design-forward contemporary pieces'
  WHEN 'wax-london' THEN 'British menswear label offering relaxed, sustainable everyday clothing'
  WHEN 'whoclo' THEN 'Emerging streetwear brand with a fresh perspective on urban fashion'
  WHEN 'worst-behaviour' THEN 'UK brand channelling raw energy and rebellious spirit into streetwear'
  WHEN 'xlarge' THEN 'LA streetwear pioneer co-founded by Beastie Boys member Mike D'
  WHEN 'yohji-yamamoto' THEN 'Legendary Japanese designer defining avant-garde fashion with dark romanticism'
  ELSE description
END
WHERE is_active = true AND (description IS NULL OR description = '');