
UPDATE brands SET history = 'Founded in 1996 in Stockholm by Jonny Johansson, Acne Studios began as a creative collective before evolving into one of Scandinavia''s most influential luxury fashion houses. Known for its minimalist aesthetic with an artistic edge, the brand spans ready-to-wear, footwear, accessories, and denim. Acne Studios has become a pillar of contemporary Scandinavian design, blending clean lines with unexpected details.' WHERE slug = 'acne-studios' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1952 by Azzedine Alaïa in Paris, Maison Alaïa is a French haute couture and ready-to-wear house celebrated for its sculptural silhouettes and masterful use of knit, leather, and stretch fabrics. Alaïa was known as the "King of Cling" for his body-conscious designs. After his passing in 2017, the house continues under the creative direction of Pieter Mulier, maintaining its legacy of craftsmanship.' WHERE slug = 'alaa' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1994 in London, AllSaints is a British contemporary fashion brand known for its rock-and-roll-inspired aesthetic. Recognisable by its signature ramskull logo and distinctive store interiors featuring walls of vintage sewing machines, AllSaints offers a dark, urban edge to everyday wardrobe staples.' WHERE slug = 'allsaints' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1949 by Kihachiro Onitsuka in Kobe, Japan, ASICS (an acronym for "Anima Sana In Corpore Sano" — a sound mind in a sound body) is one of the world''s leading performance sportswear and footwear brands. Originally known as Onitsuka Tiger, ASICS has become a favourite in both running and streetwear circles, with retro silhouettes like the Gel-Kayano and Gel-Lyte III gaining cult status.' WHERE slug = 'asics' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Established in 1894 in South Shields, England, by John Barbour, Barbour is a quintessentially British heritage brand renowned for its waxed cotton jackets and outdoor clothing. With five Royal Warrants and over 130 years of craftsmanship, Barbour has transcended its country roots to become a staple in both rural and urban wardrobes worldwide.' WHERE slug = 'barbour' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1966 in Vicenza, Italy, Bottega Veneta is an Italian luxury fashion house celebrated for its signature intrecciato leather weaving technique. Under creative director Matthieu Blazy, the brand continues to push the boundaries of quiet luxury with innovative materials and refined craftsmanship, offering a discreet alternative to logo-heavy fashion.' WHERE slug = 'bottega-veneta' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1889 by Hamilton Carhartt in Detroit, Michigan, Carhartt was originally a workwear brand for manual labourers. Carhartt WIP (Work In Progress), launched in 1989 in Europe, reimagined the brand''s rugged staples for streetwear and urban culture. With its durable fabrics and utilitarian silhouettes, Carhartt WIP became a cornerstone of European streetwear.' WHERE slug = 'carhartt-wip' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Launched in 1983 by Casio, G-Shock was born from engineer Kikuo Ibe''s mission to create an unbreakable watch. Known for its shock resistance, water resistance, and bold designs, G-Shock has become a cultural icon embraced by streetwear enthusiasts, military personnel, and athletes worldwide. The brand regularly collaborates with fashion labels and artists.' WHERE slug = 'casio-g-shock' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Craig Green is a British fashion designer who launched his eponymous label after graduating from Central Saint Martins in 2012. Known for his sculptural, conceptual menswear that blurs the line between fashion and art, Green''s collections often feature geometric constructions, layered fabrics, and workwear-inspired silhouettes. He has won multiple fashion awards including the BFC/GQ Designer Menswear Fund.' WHERE slug = 'craig-green' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Daiki Suzuki in New York in 1999, Engineered Garments draws on American workwear, military, and utilitarian traditions filtered through a distinctly Japanese lens. The brand is celebrated for its meticulous construction, unexpected fabric choices, and pattern-mixing. Part of the Nepenthes family, it has become a cornerstone of the Americana-meets-Japanese-craft aesthetic.' WHERE slug = 'engineered-garments' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Erdem Moralioglu founded his eponymous label in London in 2005. Known for his romantic, garden-inspired prints and intricate lacework, Erdem creates collections that blend ethereal femininity with a modern sensibility. The Canadian-born, British-based designer has dressed royalty and celebrities alike, becoming one of London Fashion Week''s most anticipated shows.' WHERE slug = 'erdem' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Fear of God was founded by Jerry Lorenzo in 2013 in Los Angeles. The mainline embodies a refined, luxury-meets-streetwear vision, while ESSENTIALS, launched in 2018, offers a more accessible range of elevated basics. Known for its oversized silhouettes, neutral palette, and relaxed California aesthetic, ESSENTIALS has become one of the most recognisable contemporary brands globally.' WHERE slug = 'fear-of-god-essentials' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Issey Miyake in 1970 in Tokyo, the house is renowned for its technology-driven design philosophy and innovative pleating techniques, most notably the iconic Pleats Please line. Miyake''s work bridges fashion, art, and engineering, creating garments that move with the body. His legacy continues to inspire through a design ethos rooted in "making things."' WHERE slug = 'issey-miyake' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Jordan Brand was born from Nike''s partnership with Michael Jordan, launching the first Air Jordan sneaker in 1985. What started as a signature basketball shoe became a global cultural phenomenon spanning sportswear, streetwear, and luxury fashion. The Jumpman logo is one of the most recognised symbols in the world, and Jordan releases continue to drive sneaker culture.' WHERE slug = 'jordan-brand' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Jonathan Anderson in 2008 in London, JW Anderson is known for its boundary-pushing, gender-fluid approach to fashion. Anderson''s designs are playful yet intellectual, often incorporating sculptural shapes and unexpected details. He simultaneously serves as creative director of Loewe, making him one of the most influential designers of his generation.' WHERE slug = 'jw-anderson' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Ronnie Fieg in 2011 in New York City, Kith began as a sneaker boutique before expanding into a full lifestyle brand. Known for its premium collaborations with brands like Nike, New Balance, and BMW, Kith blends streetwear with luxury sensibility. Its flagship stores and Kith Treats cereal bar have become cultural landmarks.' WHERE slug = 'kith' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Christophe Lemaire in 1991 in Paris, Lemaire (formerly known as Christophe Lemaire) is a French fashion house celebrated for its understated elegance and fluid silhouettes. Lemaire served as artistic director of Hermès womenswear from 2010 to 2014. The brand, co-led with Sarah-Linh Tran, champions a timeless, effortlessly chic wardrobe rooted in comfort and quality fabrics.' WHERE slug = 'lemaire' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1906 in Boston by William J. Riley, New Balance began as an arch support company before becoming one of the world''s leading athletic footwear brands. Proudly maintaining US and UK manufacturing, New Balance has experienced a cultural renaissance in recent years, with models like the 550, 2002R, and 990 series becoming streetwear staples through collaborations with Aimé Leon Dore, JJJJound, and others.' WHERE slug = 'new-balance' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Phil Knight and Bill Bowerman in 1964 as Blue Ribbon Sports before becoming Nike in 1971, the brand is the world''s largest sportswear company. Named after the Greek goddess of victory, Nike revolutionised athletic footwear and apparel through innovation, athlete partnerships, and iconic marketing. The Swoosh is one of the most recognised logos on the planet.' WHERE slug = 'nike' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 2005 by Jockum Hallin and Cristopher Nying in Gothenburg, Sweden, Our Legacy is a contemporary brand known for its Scandinavian sensibility blended with a rebellious, subcultural edge. The brand offers thoughtfully designed pieces that age well, drawing from punk, post-punk, and workwear traditions. Our Legacy WORK SHOP serves as its experimental retail concept.' WHERE slug = 'our-legacy' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 2015 by Francesco Ragazzi in Milan, Palm Angels draws inspiration from LA skate culture and Italian luxury. Originally conceived as a photography project documenting the skateboarding scene, it evolved into a full fashion label. Palm Angels blends streetwear energy with high-end craftsmanship, becoming a favourite of the hip-hop and fashion communities.' WHERE slug = 'palm-angels' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1948 by Rudolf Dassler in Herzogenaurach, Germany, PUMA is one of the world''s largest sportswear companies. Born from the split between the Dassler brothers (the other founding Adidas), PUMA has a rich heritage in football, motorsport, and track and field. The brand has successfully bridged sport and fashion through collaborations with Rihanna, A$AP Rocky, and others.' WHERE slug = 'puma' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Rhuigi Villaseñor in 2015 in Los Angeles, Rhude blends American sportswear and luxury fashion with the designer''s Filipino and Saudi Arabian heritage. Known for its graphic-heavy aesthetic, bandana prints, and the iconic Rhecess sneaker, Rhude has rapidly risen from a cult streetwear label to a presence on the global luxury stage.' WHERE slug = 'rhude' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Rick Owens launched his eponymous label in 1994 in Los Angeles before relocating to Paris. Known as the "Lord of Darkness," Owens creates avant-garde fashion characterised by elongated silhouettes, draped fabrics, and a monochromatic, brutalist aesthetic. His work has profoundly influenced contemporary fashion, and his shows are considered performance art events.' WHERE slug = 'rick-owens' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Simone Rocha founded her label in 2010 after graduating from Central Saint Martins. The Irish-born, London-based designer is celebrated for her romantic, darkly feminine collections that combine intricate embroidery, tulle, and pearl embellishments with structured silhouettes. Her work draws deeply from her Irish heritage and has earned her a devoted global following.' WHERE slug = 'simone-rocha' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Kim Kardashian in 2019, SKIMS is a shapewear and clothing brand that has rapidly expanded into loungewear, swimwear, and menswear. Known for its inclusive size range and innovative fabrics, SKIMS has disrupted the intimates market and achieved a multi-billion-dollar valuation, becoming one of the fastest-growing brands in fashion.' WHERE slug = 'skims' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1982 by Massimo Osti in Ravarino, Italy, Stone Island is renowned for its obsessive fabric research and experimental dyeing techniques. The brand''s iconic compass badge has become a symbol of football casuals culture and streetwear alike. Stone Island pushes the boundaries of textile innovation, creating garments that change colour with temperature or glow in the dark.' WHERE slug = 'stone-island' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1949 in Yamaguchi, Japan, by Tadashi Yanai''s father, UNIQLO (short for "Unique Clothing") has grown into one of the world''s largest casual wear retailers. Known for its LifeWear philosophy — simple, high-quality everyday clothing — UNIQLO is celebrated for innovative fabrics like HeatTech and AIRism, and collaborations with designers such as Jil Sander and Christophe Lemaire.' WHERE slug = 'uniqlo' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1966 by Paul Van Doren in Anaheim, California, Vans is an iconic American footwear and apparel brand rooted in skateboarding, BMX, and youth culture. The Old Skool, Authentic, and Sk8-Hi are among the most recognisable sneakers ever made. Vans'' "Off The Wall" ethos has made it a permanent fixture in streetwear, punk, and alternative culture.' WHERE slug = 'vans' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Grace Wales Bonner in 2014 after graduating from Central Saint Martins, Wales Bonner explores the African diaspora through a luxury lens. The British-Jamaican designer blends European tailoring with Caribbean and African cultural references, creating collections that are both deeply personal and universally acclaimed. Her adidas collaborations have become some of the most coveted in sneaker culture.' WHERE slug = 'wales-bonner' AND (history IS NULL OR history = '');
