
UPDATE brands SET history = 'Antihero Skateboards was founded in 1995 by professional skateboarder Julien Stranger in San Francisco. A rider-owned brand under the Deluxe Distribution umbrella, Antihero is known for its irreverent, anti-establishment attitude and raw, punk-influenced graphics. It remains one of the most respected and authentic skateboard companies in the world.' WHERE slug = 'antihero' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 2011 by Sofia Prantera in London, ARIES combines streetwear sensibilities with a punk DIY ethos. The brand is known for its bold graphics, tie-dye techniques, and gender-fluid approach. Prantera, who previously co-founded Silas, brings decades of subcultural experience to a brand that bridges skate, rave, and fashion.' WHERE slug = 'aries' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Ashley Williams is a London-based designer who launched her label in 2012 after graduating from the University of Westminster. Known for her playful, irreverent designs that draw from pop culture, horror films, and British subcultures, Williams has built a loyal following with her bold graphics and kitschy-cool aesthetic.' WHERE slug = 'ashley-williams' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 1976 in Tokyo, BEAMS started as a small shop in Harajuku before becoming one of Japan''s most influential multi-brand retailers and fashion labels. BEAMS curates and creates collections that blend American and European influences with Japanese attention to detail. Its various sub-labels and collaborations have made it a cornerstone of Japanese fashion culture.' WHERE slug = 'beams' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Beyond Retro was founded in 2002 in London as a vintage clothing retailer, quickly becoming one of the UK''s largest purveyors of secondhand fashion. Known for its hand-picked collections spanning multiple decades, Beyond Retro also pioneered its own upcycled label, transforming vintage stock into contemporary designs. It has become a go-to destination for sustainable, one-of-a-kind fashion.' WHERE slug = 'beyond-retro' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Cactus Jack is the creative label and brand of rapper, designer, and cultural phenomenon Travis Scott. Launched as both a record label and fashion imprint, Cactus Jack is known for its high-profile collaborations with Nike, Jordan Brand, McDonald''s, and more. The brand represents Scott''s vision of merging music, fashion, and consumer culture into one immersive universe.' WHERE slug = 'cactus-jack' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Chopova Lowena was founded in 2017 by Emma Chopova and Laura Lowena, blending Bulgarian folk traditions with London''s punk and rave scenes. The brand is known for its signature carabiner-belted pleated skirts and upcycled fabrics. Winners of the LVMH Prize and BFC/Vogue Designer Fashion Fund, Chopova Lowena represents a bold new wave of sustainable, culturally rich fashion.' WHERE slug = 'chopova-lowena' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Fragment Design was founded by Hiroshi Fujiwara in 1994 in Tokyo. Widely regarded as the godfather of streetwear, Fujiwara''s influence spans music, fashion, and design. Fragment''s signature double lightning bolt logo has appeared on collaborations with Nike, Louis Vuitton, Moncler, and countless others, making it one of the most prolific and respected names in collaborative fashion.' WHERE slug = 'fragment-design' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Girls Don''t Cry is a streetwear label created by Japanese artist and designer Verdy (real name Verdyhan) in 2017. Known for its butterfly logo and positive messaging, the brand sits alongside Verdy''s other project, Wasted Youth. Girls Don''t Cry has gained a massive global following through limited drops and collaborations with Nike, Human Made, and others.' WHERE slug = 'girls-dont-cry' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Kiko Kostadinov is a Bulgarian-born, London-based designer who launched his menswear label in 2016 after graduating from Central Saint Martins. Known for his technical, deconstructed approach to tailoring and sportswear, Kostadinov has developed cult status through his ASICS footwear collaborations and his innovative approach to functional fashion. His womenswear line is co-designed by Laura and Deanna Fanning.' WHERE slug = 'kiko-kostadinov' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Hardy Blechman in 1994 in London, Maharishi is a pioneering streetwear brand rooted in military surplus, Eastern philosophy, and sustainability. Known for its embroidered camo patterns, upcycled military garments, and dragon motifs, Maharishi was one of the first streetwear brands to champion organic and recycled fabrics.' WHERE slug = 'maharishi' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Marine Serre is a French fashion designer who launched her label in 2017 after winning the LVMH Prize. Known for her signature crescent moon print and commitment to upcycling, Serre creates collections that blend futurism with environmental consciousness. Her work has defined a new wave of sustainability-forward luxury fashion.' WHERE slug = 'marine-serre' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Martine Rose is a British-Jamaican designer who founded her eponymous menswear label in 2007 in London. Known for her oversized silhouettes, subcultural references, and celebration of London''s diverse communities, Rose has become one of the most influential designers of her generation. Her Nike collaborations and runway shows set in unexpected London locations have earned cult status.' WHERE slug = 'martine-rose' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Neighborhood was founded by Shinsuke Takizawa in 1994 in Tokyo''s Harajuku district. Rooted in motorcycle culture, military aesthetics, and Americana, Neighborhood is a pillar of the Ura-Harajuku movement. The brand is known for its dark, rugged aesthetic and collaborations with adidas, Converse, and other streetwear labels.' WHERE slug = 'neighborhood' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded by Brendon Babenzien in 2015 in New York City, Noah is a menswear brand that blends preppy Americana with punk attitude and environmental activism. Babenzien, formerly creative director of Supreme, created Noah to prove that fashion can be both stylish and socially responsible. The brand champions sustainability, fair labour practices, and community engagement.' WHERE slug = 'noah' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'NOCTA is a Nike sub-label created in collaboration with Drake, launched in 2020. Named after Drake''s nocturnal creative process, the line delivers performance-meets-lifestyle apparel and footwear designed for after-hours culture. NOCTA blends Nike''s athletic innovation with Drake''s personal style, offering elevated essentials with a focus on versatility.' WHERE slug = 'nocta-drakenike' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Patta was founded in 2004 by Edson Sabajo and Guillaume Schmidt in Amsterdam as a sneaker boutique and streetwear brand. Rooted in hip-hop, skateboarding, and football culture, Patta has grown from a small shop to an internationally recognised label. Its collaborations with Nike, New Balance, and Asics are among the most sought-after releases in sneaker culture.' WHERE slug = 'patta' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'The Hundreds was founded in 2003 by Bobby Hundreds (Bobby Kim) and Ben Hundreds (Ben Shenassafar) in Los Angeles. Built on the intersection of streetwear, skateboarding, and punk culture, The Hundreds is known for its "Adam Bomb" mascot and graphic-driven designs. The brand also operates as a media platform, telling stories that connect clothing to culture.' WHERE slug = 'the-hundreds' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Thisisneverthat is a South Korean streetwear brand founded in 2010 in Seoul. Drawing from American sportswear, workwear, and 90s nostalgia, the brand offers a distinctly Korean perspective on global street culture. Thisisneverthat has collaborated with New Balance, Converse, and Gore-Tex, and operates popular flagship stores in Seoul.' WHERE slug = 'thisisneverthat' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Founded in 2002 by Jeff Lubell, True Religion became famous for its premium denim featuring bold horseshoe stitching on the back pockets. A symbol of early-2000s celebrity culture, the brand was worn by everyone from Beyoncé to David Beckham. True Religion has experienced a resurgence in recent years, embraced by a new generation discovering Y2K fashion.' WHERE slug = 'true-religion' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Undefeated was founded in 2002 by James Bond and Eddie Cruz in Los Angeles as a premium sneaker boutique. It has since evolved into a globally recognised streetwear brand known for its five-strike logo. Undefeated''s collaborations with Nike, adidas, and Converse have produced some of the most collectible sneakers in history.' WHERE slug = 'undefeated' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Wasted Youth is a streetwear project by Japanese artist and designer Verdy, launched alongside Girls Don''t Cry. Where GDC carries a positive, soft aesthetic, Wasted Youth takes a darker, more rebellious approach inspired by punk and skate culture. The brand''s graphics and limited releases have made it a coveted name in the global streetwear scene.' WHERE slug = 'wasted-youth' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Salomon was founded in 1947 by François Salomon in Annecy, France, originally producing ski edges. The brand has since become a leader in trail running, hiking, and outdoor footwear. In recent years, Salomon has gained massive streetwear credibility, with its XT-6 and other trail silhouettes becoming fashion staples through collaborations with MM6 Maison Margiela, Palace, and others.' WHERE slug = 'salomon' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'On was founded in 2010 in Zurich, Switzerland, by Olivier Bernhard, David Allemann, and Caspar Coppetti. Known for its signature CloudTec cushioning technology, On has rapidly grown from a running shoe startup to a global performance brand. Its sleek, minimalist designs have crossed over into fashion, with a collaboration with Roger Federer and the Roger line elevating its style credentials.' WHERE slug = 'on' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'FatFace was founded in 1988 by Tim Slade and Jules Leaver, who sold T-shirts and sweatshirts from a bar in the French Alps to fund their skiing. Named after La Face, a challenging black run in Val d''Isère, FatFace has grown into a beloved British lifestyle brand offering casual clothing and accessories inspired by outdoor living.' WHERE slug = 'fatface' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Perks and Mini (P.A.M.) was founded in 2000 by Misha Hollenbach and Shauna Toohey in Melbourne, Australia. The brand operates at the intersection of art, music, and fashion, drawing from psychedelia, underground subcultures, and DIY ethics. P.A.M.''s bold graphics and experimental approach have earned it a devoted international following.' WHERE slug = 'perks-and-mini' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Pigalle is a Parisian fashion and basketball brand founded by Stéphane Ashpool in 2008, named after the vibrant neighbourhood where he grew up. The brand gained global recognition for its iconic basketball court wedged between apartment buildings in the 9th arrondissement. Pigalle blends sport, street, and high fashion with a deeply personal, community-driven approach.' WHERE slug = 'pigalle' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Pop Trading Company was founded in 2013 by Peter Kolkman and Ric van Rest in Amsterdam. Rooted in skateboarding, the brand combines functional skate apparel with clean, European-influenced design. Pop has built a reputation for quality and understated style, collaborating with Converse, Vans, and Carhartt WIP.' WHERE slug = 'pop-trading-company' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Jaded London was founded in 2013 by brothers Jade and Grant Faiers in East London. Known for its bold, statement-making pieces including sequin trousers, patchwork denim, and festival-ready looks, Jaded London has become a go-to for Gen-Z fashion. The brand thrives on social media and champions a loud, maximalist aesthetic.' WHERE slug = 'jaded-london' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Auralee is a Japanese fashion label founded by Ryota Iwai in 2015 in Tokyo. The brand is celebrated for its meticulous attention to fabric development, working directly with Japanese mills to create unique textiles. Auralee''s collections are defined by soft, natural colours, relaxed silhouettes, and a quiet luxury that has earned a devoted international following.' WHERE slug = 'auralee' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Herno was founded in 1948 by Giuseppe Marenzi in Lesa, on the shores of Lake Maggiore in Italy. Originally specialising in raincoats, Herno has evolved into a luxury outerwear brand known for its technical fabrics and refined Italian craftsmanship. Its Laminar line focuses on high-performance, waterproof and breathable garments for urban and outdoor environments.' WHERE slug = 'herno' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Rokit is a London-based vintage clothing store founded in 1986 in Camden Town. One of the UK''s original vintage retailers, Rokit curates hand-picked collections of secondhand clothing spanning decades of fashion history. With multiple locations across London, Rokit has been at the forefront of the vintage and sustainability movement in British fashion.' WHERE slug = 'rokit' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Shushu/Tong is a Shanghai-based womenswear label founded by Liushu Lei and Yutong Jiang in 2015 after studying at Central Saint Martins. The brand explores girlhood and femininity through oversized bows, romantic silhouettes, and a subversive sweetness. Shushu/Tong has quickly gained international recognition and is stocked in major retailers worldwide.' WHERE slug = 'shushutong' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Takashi Murakami is a Japanese contemporary artist known for his Superflat art movement, colourful flower motifs, and collaborations that bridge fine art and commercial culture. His partnership with Louis Vuitton in 2003 produced one of the most iconic fashion collaborations in history. Murakami''s influence extends across fashion, music, and pop culture globally.' WHERE slug = 'takashi-murakami' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Manière De Voir is a Manchester-based fashion brand founded in 2014. The brand offers trend-driven, affordable luxury pieces spanning menswear and womenswear, with a focus on contemporary streetwear silhouettes, premium fabrication, and a distinctive dark aesthetic. It has built a strong direct-to-consumer presence through social media.' WHERE slug = 'maniere-de-voir' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'Heresy is a London-based brand founded by Liam Maybank that draws from British folklore, paganism, and occult imagery. Blending streetwear with esoteric symbolism, Heresy creates collections inspired by ancient traditions, ritual, and the British landscape. The brand occupies a unique niche where subcultural fashion meets mythological storytelling.' WHERE slug = 'heresy' AND (history IS NULL OR history = '');

UPDATE brands SET history = 'size? is a UK-based sneaker and streetwear retailer founded in 2000, operating as part of the JD Sports Fashion group. Known for its exclusive sneaker collaborations and in-depth product storytelling, size? has become one of Europe''s most respected sneaker destinations, regularly partnering with Nike, adidas, New Balance, and other major footwear brands.' WHERE slug = 'size' AND (history IS NULL OR history = '');
